### ISSUE TITLE
publishing

### ISSUE THREAD

**Issue by rjriel** [qlik-oss/core-grpc-mongodb-connector#78]
Has there been any thought put into adding the image for this to the `qlikcore` entity on docker hub? Or some other way to package and distribute?

**Comment by sublibra** [comment]
None so far but there shouldn't be an issue doing it long as we are clear that it is an example and not a full productified connector

**Comment by sublibra** [comment]
After discussion within the team we decided to not publish on docker hub. Reason being to ensure we don't confuse our users by publishing examples.
